# Generated by Django 4.2.4 on 2024-09-30 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deleted', 'Deleted'), ('formed', 'Formes'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(max_length=100)),
                ('importance_score', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Researchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=25, null=True)),
                ('years_of_life', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('major_discovery', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RequestResearchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_primary', models.BooleanField(default=True)),
                ('explorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.researchers')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discovery.request')),
            ],
        ),
    ]
