# Generated by Django 4.2.4 on 2024-09-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchers',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
