# Generated by Django 4.2.4 on 2024-09-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_researchers_long_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchers',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
