# Generated by Django 4.2.4 on 2024-10-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_alter_researchers_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='importance_score',
        ),
    ]
