# Generated by Django 4.2.4 on 2024-10-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_remove_request_importance_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestresearchers',
            name='quantity',
        ),
    ]
