# Generated by Django 4.2.4 on 2024-11-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_discoverers_discovery_discoverydiscoverers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='discoverers',
            field=models.ManyToManyField(related_name='discoveries', through='discovery.DiscoveryDiscoverers', to='discovery.discoverers'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
