# Generated by Django 4.2.4 on 2025-02-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0007_discovery_discoverers_alter_discovery_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
